# Use the Infinispan Dev Service in dev and test
quarkus.infinispan-client.devservices.enabled=false
quarkus.infinispan-client.server-list=localhost:11222
quarkus.infinispan-client.auth-username=admin
quarkus.infinispan-client.auth-password=password

## Docker 4 Mac workaround
quarkus.infinispan-client.client-intelligence=BASIC